/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,svelte,vue}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'secondary-container': '#394c51',
        'on-tertiary': '#15353c',
        'outline-variant': '#584237',
        'on-background': '#d2e5f2',
        'primary-container': '#f37221',
        outline: '#a78b7e',
        'inverse-surface': '#d2e5f2',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdbcb',
        'on-surface-variant': '#dfc0b2',
        'surface-tint': '#ffb691',
        'on-primary-container': '#552000',
        'secondary-fixed-dim': '#b5cacf',
        'on-tertiary-fixed-variant': '#2d4b53',
        'surface-container-highest': '#253741',
        'tertiary-fixed-dim': '#acccd5',
        'on-surface': '#d2e5f2',
        'surface-bright': '#2a3b45',
        'on-primary-fixed': '#341100',
        surface: '#03151e',
        'on-secondary-fixed': '#0a1e22',
        'on-secondary-container': '#a7bcc1',
        'secondary-fixed': '#d1e6eb',
        primary: '#ffb691',
        background: '#03151e',
        'surface-container-lowest': '#001019',
        'surface-container-low': '#0b1e27',
        'inverse-on-surface': '#21333c',
        'on-tertiary-fixed': '#001f26',
        'error-container': '#93000a',
        'tertiary-container': '#7e9da6',
        secondary: '#b5cacf',
        'surface-dim': '#03151e',
        'on-primary-fixed-variant': '#793100',
        'surface-variant': '#253741',
        'surface-container': '#10222b',
        'on-primary': '#552000',
        'inverse-primary': '#9e4200',
        'tertiary-fixed': '#c8e8f1',
        tertiary: '#acccd5',
        'on-secondary': '#203337',
        'surface-container-high': '#1a2c36',
        'on-secondary-fixed-variant': '#374a4e',
        error: '#ffb4ab',
        'primary-fixed-dim': '#ffb691',
        'on-tertiary-container': '#15343c',
        'on-tertiary-fixed': '#001f26',
        'secondary-container': '#394c51',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Barlow Condensed', 'sans-serif'],
        display: ['Barlow Condensed', 'sans-serif'],
        body: ['Barlow', 'sans-serif'],
        label: ['DM Mono', 'monospace'],
        nav: ['DM Mono', 'monospace'],
        mono: ['DM Mono', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '700' }],
      },
      spacing: {
        md: '16px',
        xl: '40px',
        sm: '8px',
        base: '4px',
        lg: '24px',
        xs: '4px',
        gutter: '16px',
        margin: '24px',
      },
    },
  },
  plugins: [],
};
